### ISSUE TITLE
Install not completing on OpenShift

### ISSUE THREAD

**Issue by kylebuch8** [kylebuch8/rh-search-openshift#1]
`Cloning "https://github.com/kylebuch8/rh-search-openshift.git" ...
	Commit:	434b95f9cf6b39d9a15375c3e71cffe754b5fb7e (an 11th try)
	Author:	Kyle Buchanan <kylebuch8@gmail.com>
	Date:	Thu May 4 17:20:16 2017 -0400
Pulling image "registry.access.redhat.com/rhscl/nodejs-6-rhel7@sha256:xxxxxxx" ...
Pulling image "registry.access.redhat.com/rhscl/nodejs-6-rhel7@sha256:xxxxxxx" ...
---> Installing application source ...
---> Building your Node application from source
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/libexec/s2i/assemble: line 51:    12 Killed                  npm install
error: build error: non-zero (13) exit code from registry.access.redhat.com/rhscl/nodejs-6-rhel7@sha256:xxxxxxx`

**Comment by dileepab** [comment]
Same here.

**Comment by sudipta26889** [comment]
`---> Installing application source ...
---> Building your Node application from source
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated native-or-bluebird@1.1.2: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
/usr/libexec/s2i/assemble: line 51:    13 Killed                  npm install
error: build error: non-zero (13) exit code from registry.access.redhat.com/rhscl/nodejs-6-`
Getting same issue.

**Comment by jgabe** [comment]
same here:


Pulling image "registry.access.redhat.com/rhscl/nodejs-6-rhel7@sha256:b84c9a9027eab85386fc9ef12044c44ab8f622916e7232ecfe1486398d11b490" ...
Pulling image "registry.access.redhat.com/rhscl/nodejs-6-rhel7@sha256:b84c9a9027eab85386fc9ef12044c44ab8f622916e7232ecfe1486398d11b490" ...
---> Installing application source ...
---> Building your Node application from source
/usr/libexec/s2i/assemble: line 51:    12 Killed                  npm install
error: build error: non-zero (13) exit code from registry.access.redhat.com/rhscl/nodejs-6-rhel7@sha256:b84c9a9027eab85386fc9ef12044c44ab8f622916e7232ecfe1486398d11b490

**Comment by glenmesso** [comment]
Hi, did this go anywhere?

Thanks
